// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytywpxlbodpkbelowmxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0eXdweGxib2Rwa2JlbG93bXhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0MDczODYsImV4cCI6MjA3Njk4MzM4Nn0.gJd0JQ5ok64WlWPTXf41-KHGQJ-K5eZDsE7scO6EJSc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});